In [3]:
1-1


0

In [6]:
list=("shahid","khan",23)
type(list)

tuple

In [2]:
import numpy as np

In [5]:
list=[1,3,4,5,]

arr=np.array(list)

In [7]:
type(arr)

numpy.ndarray

In [9]:
arr.shape


(4,)

In [12]:
arr1=np.array([[1,3,2],[4,5,6]])
#2 rows 3 columns, so it is called 2 dimension

In [14]:
arr1.shape

(2, 3)

In [19]:
arr1.reshape(1,6)

array([[1, 3, 2, 4, 5, 6]])

In [20]:
arr1.shape

(2, 3)

In [21]:
arr1

array([[1, 3, 2],
       [4, 5, 6]])

In [22]:
arr1.dtype

dtype('int32')

In [29]:
np.arange(1,10,2).reshape(1,5)

array([[1, 3, 5, 7, 9]])

In [31]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [52]:
np.linspace(1,20,40)

array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
        3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
        5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
        8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
       10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
       13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
       15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
       18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ])

In [42]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [46]:
5+np.ones((2,3))

array([[6., 6., 6.],
       [6., 6., 6.]])

In [48]:
np.eye(3) # identity matrix


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
np.random.rand(2,3)

array([[0.68931114, 0.67060873, 0.93705096],
       [0.32164187, 0.15700812, 0.07371455]])

In [56]:
print("random number following a noraml distrubution with mean=0 and std=1")
print(np.random.randn(5,3))

random number following a noraml distrubution with mean=0 and std=1
[[ 0.88419086  2.05028618  1.54241057]
 [ 0.83170384  0.11205866 -0.11833125]
 [ 0.33789383  0.76961318  1.13606517]
 [ 0.85715002  1.94864054 -1.9313835 ]
 [ 0.27968371 -0.5893054  -0.47122902]]


In [58]:
np.random.randint(1,100,(4,4))

array([[ 5, 91, 17, 99],
       [34, 27, 53, 44],
       [79, 17, 57, 64],
       [54, 44, 86, 20]])

In [59]:
arr=np.arange(0,11)

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr[-1:2:-2]

array([10,  8,  6,  4])

In [67]:
arr2=np.random.randint(2,100,20).reshape(5,4)

In [68]:
arr2

array([[16, 15, 64, 70],
       [38, 47, 79, 60],
       [34, 19, 66, 56],
       [76, 47, 82, 70],
       [ 5, 92, 21, 47]])

In [70]:
arr2[0:3]

array([[16, 15, 64, 70],
       [38, 47, 79, 60],
       [34, 19, 66, 56]])

In [71]:
arr2[0:3,0:3]

array([[16, 15, 64],
       [38, 47, 79],
       [34, 19, 66]])

In [77]:
arr2[3:,1:,]

array([[47, 82, 70],
       [92, 21, 47]])

In [79]:
arr2

array([[16, 15, 64, 70],
       [38, 47, 79, 60],
       [34, 19, 66, 56],
       [76, 47, 82, 70],
       [ 5, 92, 21, 47]])

In [83]:
arr2[2:4,1:3]

array([[19, 66],
       [47, 82]])

In [87]:
arr2[2:4,0:-0]

array([], shape=(2, 0), dtype=int32)

In [88]:
#universal operation

In [93]:
arr1=np.random.randint(0,100,(3,3))
arr2=np.random.randint(0,100,(3,3))

In [96]:
arr1


array([[64, 86, 97],
       [ 5, 62, 70],
       [ 4, 46,  4]])

In [97]:
arr2

array([[16, 97, 54],
       [34, 18, 25],
       [29, 75, 67]])

In [98]:
arr1+arr2

array([[ 80, 183, 151],
       [ 39,  80,  95],
       [ 33, 121,  71]])

In [99]:
arr1*arr2

array([[1024, 8342, 5238],
       [ 170, 1116, 1750],
       [ 116, 3450,  268]])

In [103]:
np.sqrt(arr2)

array([[4.        , 9.8488578 , 7.34846923],
       [5.83095189, 4.24264069, 5.        ],
       [5.38516481, 8.66025404, 8.18535277]])

In [105]:
np.exp(arr2)

array([[8.88611052e+06, 1.33833472e+42, 2.83075330e+23],
       [5.83461743e+14, 6.56599691e+07, 7.20048993e+10],
       [3.93133430e+12, 3.73324200e+32, 1.25236317e+29]])

In [106]:
np.log(arr2)

array([[2.77258872, 4.57471098, 3.98898405],
       [3.52636052, 2.89037176, 3.21887582],
       [3.36729583, 4.31748811, 4.20469262]])

In [108]:
arr1=np.arange (1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
arr1[2:]1000

array([[1004, 1046, 1004]])